# Generated by Django 4.2.3 on 2023-08-07 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_choice_alter_productitem_choice'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Male'), (2, 'Female')], default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='Custumer'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.IntegerField(choices=[(0, 'Staff'), (1, 'Seller'), (2, 'Customer')], default=2),
        ),
        migrations.CreateModel(
            name='MyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_product', to='product.product')),
            ],
        ),
    ]
