# Generated by Django 4.2.3 on 2023-07-19 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=221)),
                ('product_name', models.CharField(max_length=220)),
                ('prod_img', models.ImageField(upload_to='product_item/')),
                ('description', models.TextField()),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zona_product_item', to='category.zona')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('choice', models.IntegerField(choices=[(0, 'KG'), (1, 'COUNT')], default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_item', to='product.product')),
            ],
        ),
    ]
