# Generated by Django 4.2.3 on 2023-07-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='choice',
            field=models.IntegerField(choices=[(1, 'SUM'), (2, '$')], default=1),
        ),
    ]
