# Generated by Django 4.2.3 on 2023-07-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_choice_alter_productitem_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='choice',
            field=models.IntegerField(choices=[(1, 'SUM'), (2, '$')], default=1),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='choice',
            field=models.IntegerField(choices=[(1, 'KG'), (2, 'COUNT')], default=1),
        ),
    ]
