# Generated by Django 4.2.3 on 2023-07-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_remove_order_client_order_address_alter_order_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='carts',
            new_name='cart',
        ),
    ]
