# Generated by Django 4.2.3 on 2023-07-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_rename_carts_cartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart',
            new_name='carts',
        ),
    ]
