# Generated by Django 4.2.3 on 2023-07-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_cartitem_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='prod',
        ),
    ]
